name: whatsapp_clone
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  firebase_auth: ^5.2.0
  firebase_core: ^3.4.0
  cloud_firestore: ^5.4.0
  firebase_storage: ^12.2.0
  intl_phone_number_input: ^0.7.4
  gap: ^3.0.1
  logger: ^2.4.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  file_picker: ^8.0.7
  path_provider: ^2.1.4
  dio: ^5.7.0
  open_filex: ^4.5.0
  universal_html: ^2.2.4
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  camera: ^0.11.0+2
  path: ^1.9.0
  video_player: ^2.9.1
  image: ^4.2.0
  cached_network_image: ^3.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets\backgroundImage.png