// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxe6VaUAjfORqYL3uCyG3MT69uuoRbVtY',
    appId: '1:24272709212:web:3f13e020e1a074b3e96899',
    messagingSenderId: '24272709212',
    projectId: 'whatsapp-clone-60a51',
    authDomain: 'whatsapp-clone-60a51.firebaseapp.com',
    storageBucket: 'whatsapp-clone-60a51.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFye0hAycJN9WAgTQavdWu5i5_XtcNTKA',
    appId: '1:24272709212:android:b4cabb7d47d8e18ce96899',
    messagingSenderId: '24272709212',
    projectId: 'whatsapp-clone-60a51',
    storageBucket: 'whatsapp-clone-60a51.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6sSAP5NkzxxytZFJ4CIKpiMMEpYo5ziA',
    appId: '1:24272709212:ios:3d7098c4d46ec256e96899',
    messagingSenderId: '24272709212',
    projectId: 'whatsapp-clone-60a51',
    storageBucket: 'whatsapp-clone-60a51.appspot.com',
    iosBundleId: 'com.zouheirn.whatsappclone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6sSAP5NkzxxytZFJ4CIKpiMMEpYo5ziA',
    appId: '1:24272709212:ios:007d87110f0f1aa7e96899',
    messagingSenderId: '24272709212',
    projectId: 'whatsapp-clone-60a51',
    storageBucket: 'whatsapp-clone-60a51.appspot.com',
    iosBundleId: 'com.zouheirn.whatsappclone.whatsappClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxe6VaUAjfORqYL3uCyG3MT69uuoRbVtY',
    appId: '1:24272709212:web:d85e9049946f3363e96899',
    messagingSenderId: '24272709212',
    projectId: 'whatsapp-clone-60a51',
    authDomain: 'whatsapp-clone-60a51.firebaseapp.com',
    storageBucket: 'whatsapp-clone-60a51.appspot.com',
  );
}
